# Generated by Django 4.0.3 on 2023-12-10 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YourModel',
            new_name='UserModel',
        ),
    ]
